# gitleaks configuration for unipm
# https://github.com/gitleaks/gitleaks

title = "unipm gitleaks config"

[allowlist]
  description = "global allowlist"
  paths = [
    '''testdata/''',
    '''_test\.go$''',
    '''\.md$''',
    '''\.feature$''',
    '''go\.sum$''',
  ]
